- name: Setup ubuntu developer environment
  hosts: localhost
  connection: local
  vars:
    ssh_key_filename: id_rsa
  tasks:
    - name: Creating SSH directory
      file:
        path: /tmp/.ssh
        state: directory
    - name: generate SSH key "{{ssh_key_filename}}"
      openssh_keypair:
        path: "/tmp/.ssh/{{ssh_key_filename}}"
        type: rsa
        size: 4096
        state: present
        force: no
    - name: Install git package
      apt:
        name: git
        state: present
