- name: Setup ubuntu developer environment
  hosts: localhost
  connection: local
  vars:
    ssh_key_filename: id_rsa
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: Creating SSH directory
      file:
        path: ~/.ssh
        state: directory
    - name: generate SSH key "{{ssh_key_filename}}"
      openssh_keypair:
        path: "~/.ssh/{{ssh_key_filename}}"
        type: rsa
        size: 4096
        state: present
        force: no
    - name: Install build-ssential package
      apt:
        name: build-essential
        state: present
    - name: Install dkms package
      become: true
      apt:
        name: dkms
        state: present
    - name: Checking kernel version
      command: uname -r
      register: kernel_version
    - name: Install linux-header package
      apt:
        name: linux-headers-{{kernel_version.stdout}}
        state: present
    - name: Install git package
      apt:
        name: git
        state: present
    - name: Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-11-jdk
