#!/bin/bash

echo "Installing cowsay"
sudo apt-get install cowsay
echo "Adding ansible ppa to repository list"
sudo apt-add-repository ppa:ansible/ansible
echo "Updating apt package repository"
sudo apt-get update
echo "Installing ansible"
sudo apt-get install ansible
echo "Running ansible playbook"
ansible-playbook ansible-playbook.yml
