#!/bin/bash

source common/common.sh

echo_blue "Adding ansible ppa to repository list"
sudo apt-add-repository ppa:ansible/ansible
echo_blue "Updating apt package repository"
sudo apt-get update
install_apt_package software-properties-common cowsay lolcat ansible
echo_blue "Running ansible playbook"
ansible-playbook ansible-playbook.yml
