---

- name: Install emacs
  become: true
  apt:
    name: emacs
    state: present
- name: Copy .emacs to user home directory
  copy:
    src: .emacs
    dest: ~/.emacs
- name: check if emacs package is installed
  apt:
    name: emacs
    state: present
  check_mode: true
