name: dev-environment CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-20.04:
    # Jobs will run on ubuntu-20.04
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a setup shell script
      - name: Running setup script to install packages
        run: $GITHUB_WORKSPACE/setup
        
      # Runs a single command using the runners shell
      - name: Running test_env.sh script to check all the packages are installed properly or not
        run: $GITHUB_WORKSPACE/test/test_env.sh
